[tox]
envlist = py310, py311, py312, py313, py314, coverage
no_package = True

[testenv]
description = Run tests with pytest
deps = -r requirements-dev.txt
commands =
    pytest {posargs}

[testenv:coverage]
description = Run tests with coverage and generate reports
commands =
    coverage erase
    coverage run -m pytest {posargs}
    coverage xml
    coverage report

[testenv:regenerate]
description = Regenerate expected output files for tests
deps =
commands =
    python -m testing.regenerate_expected
