[tox]
envlist = py312, coverage
no_package = True

[testenv]
deps = -r requirements-dev.txt
commands =
    pytest {posargs}

[testenv:coverage]
commands =
    coverage erase
    coverage run -m pytest {posargs}
    coverage xml
    coverage report
